---
- name: Debian | Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: Debian | Remove New Relic repo key
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
    state: absent

- name: Debian | Remove New Relic repository
  file:
    path: /etc/apt/sources.list.d/newrelic.list
    state: absent

- name: Debian | UnInstall New Relic Sysmond
  apt:
    pkg: newrelic-sysmond
    update_cache: no
    state: absent
