---
- block:
  - include: debian.yml
    when: ansible_os_family == 'Debian'

  - include: redhat.yml
    when: ansible_os_family == 'RedHat'

  - include: default.yml
    when: newrelic_loaded_os_family|default(False) == False
  when: newrelic_install

- block:
  - name: Check for newrelic_license_key
    fail:
      msg: "newrelic_license_key has not been defined"
    when: newrelic_license_key|default(False) == False

  - name: UnConfigure New Relic Sysmond
    file:
      path: /etc/newrelic/nrsysmond.cfg
      state: absent
  when: newrelic_manage
